# Generated by Django 6.0.1 on 2026-01-29 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marka')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(verbose_name='Ürün Açıklaması')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Ürün Resmi')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myapp.category', verbose_name='Kategori')),
            ],
        ),
    ]
