# Generated by Django 6.0.1 on 2026-01-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Görsel Adı (Admin Panelinde Görünür)')),
                ('image', models.ImageField(upload_to='sliders/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında mı?')),
            ],
        ),
    ]
